on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rlibbertacr.azurecr.io
        username: ${{ secrets.acr_rlibbertacr_username }}
        password: ${{ secrets.acr_rlibbertacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t rlibbertacr.azurecr.io/kastencluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push rlibbertacr.azurecr.io/kastencluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kastencluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kastenclusterbbdc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kastenclusterbbdc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kastenclusterbbdc
        container-registry-url: rlibbertacr.azurecr.io
        container-registry-username: ${{ secrets.acr_rlibbertacr_username }}
        container-registry-password: ${{ secrets.acr_rlibbertacr_password }}
        secret-name: kastenclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kastenclusterbbdc
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          rlibbertacr.azurecr.io/kastencluster:${{ github.sha }}
        imagepullsecrets: |
          kastenclustedockerauth
